### ISSUE TITLE
FR: maintainer-needed

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#1]
Thank you very much for the very useful script. 
It would be nice to have a user "maintainer-needed@gentoo.org" for packages without maintainer (this means there is literally no maintainer in the `metadata.xml`). 
As far I could see, they are not listed at the moment.

**Comment by mm1ke** [comment]
Hi,

Yes, that's a good idea :)
I already changed the scripts. The results for patchtest and patchcheck on gentoo.levelnine.at are already up-to-date. wwwtest should have updated results tomorrow.
Please have a look and let me know if it fits your needs

**Comment by jonasstein** [comment]
Thank you. I enjoyed reading your code, but even more the result.
