### ISSUE TITLE
FR: in the file list show number of lines, not bytes

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#10]
For example
http://gentoo.levelnine.at/simplechecks/gentoo_mirror_missuse/sort-by-maintainer/
has a format like
`maintainer-needed_at_g.o.txt                       13-Sep-2017 01:20                6373`

I suggest
`maintainer-needed_at_g.o.txt                       13-Sep-2017 01:20                23 ebuilds`

**Comment by mm1ke** [comment]
Yes, that would be a nice. Unfortunately this isn't simple to change. At the moment the files are presented via nginx's autoindex feature, which simple just list the files like via ```ls -l```

To show the number of files i would probably write some html sites. 
I will keep this open. It's clearly a good idea but it needs more work.

**Comment by jonasstein** [comment]
I do not know nginx. Here an idea to work with, perhaps it helps...

```
# make a header
echo "name;number of packages";

# list all files with number of lines
wc -l *

# swap columns and add ; as separator
awk ' { t = $1; $1 = $2";"; $2 = t; print; } '

# all together:
echo "name; number of packages"; wc -l * | awk ' { t = $1; $1 = $2";"; $2 = t; print; } '
```

**Comment by mm1ke** [comment]
Hi,

I've now added a new function which generate html lists.
You can look at the lists here: https://gentooqa.levelnine.at/results/checks/
For example: https://gentooqa.levelnine.at/results/checks/wwwtest/wwwtest.html

The lists won't be generated automatically each day. For now i would like to get some feedback.
Especially on the Collums to show and about the directory style.

Please have a look :)

**Comment by jonasstein** [comment]
nice, thank you. I would prefer a mono spaced font  with fixed width, and no html table.
Value -> Quantity or qty.

**Comment by mm1ke** [comment]
Just updated the output again.. Please have a look.

**Comment by jonasstein** [comment]
looks great. If the contact is sorted alphabetical, and you write them as 
```
    13 tom@example.com 
999999 bob@example.com
```

then it is better to read with the bare eye. The user can also sort with `sort` by number of entries or use the sorted mails. I think 999999 is a realistic maximum per person. We have 40k packages this would mean a project owns all packages with 20 bugs on average.

**Comment by mm1ke** [comment]
Hi,

I've updated the output. Please have a look.
The space for numbers i now 6 chars long, i guess this should be enough.

**Comment by jonasstein** [comment]
fantastic!

**Comment by mm1ke** [comment]
BTW, what do you think about the directory style.
Every check is now in the root directory while previously they where in their corresponding scriptname-folder. (if a script run more than one checks)
The naming can be changed but right now you see which scripts generates which checks. still missing are the full lists and eapistats which i think should go into a separated statistics folder.

**Comment by jonasstein** [comment]
nice. I think the old sorting with a different number of subdirs was not ideal.
Well done!

**Comment by mm1ke** [comment]
Thanks :)

I still have to improve the code a bit, but it shouldn't take to long before i'll gonna put the new sorting with html output into the main location.

**Comment by mm1ke** [comment]
OK,

small update:
Please have a look at https://gentooqa.levelnine.at/ There is a small link on the bottom which brings you too all results.  (more precisely: https://gentooqa.levelnine.at/results/ ) The Graphs brings you to the right results to, but they are a bit outdated and some are missing.

First of all, every check has it's own folder now. Secondly, i changed the naming too.

For Example: ```DUU-BUG-duplicate_uses```
**DUU**: is just a reference to the script, which was running this check. DUU -> dupuse.sh
**BUG**: means the check looks for possible Bugs. Other script's use IMP for improvements. For example i don't count unsync homepages over ebuilds as a bug, therefore fixing this is just an improvement. This however can be changed for every script. As for now it's just my understanding of what could be a bug and what could be an improvement.
**duplicate_uses**: this is just a small description which describes the check.

There are 3 subfolders.
**checks**: lists all checks running on the vm
**full_lists**: contains the full listings with all checks, also filter after BUG and IMP
**stats**: various statistics about the tree

Please have a look :)

**Comment by jonasstein** [comment]
this is useful, but the links are not highlighted as links in my browser.
![selection_478](https://user-images.githubusercontent.com/298682/36947460-5c95f880-1fcc-11e8-82cf-0f4cd5bc65c1.png)

**Comment by mm1ke** [comment]
hmm.. i don't understand.. can you show me a picture?

**Comment by mm1ke** [comment]
Ok, please reload, i think i got it :)

**Comment by mm1ke** [comment]
@jonasstein 
I've now completly revised the homepage in order to improve maintainence.
The Stats/Checks Lists are now going to be generated which makes adding new checks much simplier.
Please have a look and tell me what you think:

Some info:
If you click on the headline at the checks/stats pages you'll get the new form where you see the lines per file and not the bytes per file. In order to still open just the txt file i've added links via the "full/main/pack" links. That way everything should be available.

BTW:
I've also revised the descriptions. More importanly they are now written in the ```_vars.sh``` file (apart other information which i use to generate the pages). I'm still not very happy with them but i think it's better than before.
Patches are welcomed of course ;)

**Comment by mm1ke** [comment]
Gonna close this. It's already working as expected. Please reopen if you think it's not.
