### ISSUE TITLE
delimiter ; 

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#11]
Just found a situation where the nice `;` delimiter fails:

http://gentoo.levelnine.at/wwwtest/sort-by-maintainer/a%3Dsummary.txt
`301;sys-boot/silo;silo-1.4.14_p20120819;https://git.kernel.org/?p=linux/kernel/git/davem/silo.git;a=summary;sparc@gentoo.org:`

I am not sure which delimiter would be better.

**Comment by mm1ke** [comment]
Hmm, i see.. What do you think about ```|``` ?

**Comment by jonasstein** [comment]
sounds good. `|` is a good visual marker, and unique. Can you make a quick grep on all resulting files, if it is not yet used?

**Comment by mm1ke** [comment]
Done, ```|``` isn't used at all.
Gonna change the scripts tonight, in addition with making them use parallel

**Comment by jonasstein** [comment]
nice
