### ISSUE TITLE
FR: banned commands in EAPI x

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#12]
```
/usr/portage$ grep "EAPI" `qgrep -l einstall`
```
reveals that we have many einstall in EAPI=6 ebuilds

However einstall was banned in EAPI 6

https://dev.gentoo.org/~ulm/pms/head/pms.html#x1-13100011.3.3.2
It would be nice to scan for these too.

**Comment by mm1ke** [comment]
Hi, i've added the einstall check. The results are already live. The are 4 ebuilds who used the banned einstall in EAPI=6. I guess you found more results because ```qgrep -l einstall``` probably also finds packages who use einstalldocs.
However if my check misses some match please let me know :)

**Comment by jonasstein** [comment]
you are right... and we should ignore comment lines too...
I checked all. No broken ebuild is left.

**Comment by mm1ke** [comment]
I'm going to close this. If you find some other commands to check for please let me know :)
