### ISSUE TITLE
FR: A list of all problems per maintainer

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#17]
if developer bob wants to know if any of his packages has a problem, he hast to walk through many subfolders. 
It would be nice to have a folder, where all problems are sorted by maintainer.

I have no good idea for the representation of this data 
perhaps it is the fastest, to prepare something like

```
http://gentoo.levelnine.at/all_by_maintainer/bob_at_g_o/srctest.txt
http://gentoo.levelnine.at/all_by_maintainer/bob_at_g_o/patchtest.txt
```

**Comment by mm1ke** [comment]
Great idea, shouldn't be to difficult to implement :)

**Comment by mm1ke** [comment]
Well, the script is live and running :)

**Comment by jonasstein** [comment]
already used often. Thank you.
