### ISSUE TITLE
FR: Copy files, when task is finnished

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#19]
Sometimes there are files missing on http://gentoo.levelnine.at/*
I think this happens for a few hours, when the job is still running. 
I suggest to complete the job first and then rsync or copy or rename (?) the new files over the old ones.

**Comment by mm1ke** [comment]
Good idea, that is an area i wanted to improve anyway..

**Comment by mm1ke** [comment]
I just updated the scripts. Now they prepare the results in the tmp folder before it gets copied into the wwwdir.
