### ISSUE TITLE
FR: leading and trailing space in DESCRIPTION

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#22]
`qgrep -N 'DESCRIPTION=" '`
`qgrep -N 'DESCRIPTION=' | grep ' "$'`

lists ebuilds with leading and trailing space, which makes no sense

**Comment by mm1ke** [comment]
Nice, btw this works with other variables as well (HOMEPAGE, LICENSE, SRC_URI...) :)

**Comment by mm1ke** [comment]
This is done.
Tomorrow we should have results, following VARS get checks for the moment: DESCRIPTION LICENSE KEYWORDS IUSE RDEPEND DEPEND RESTRICT SRC_URI DOCS
This can be easily extended :)

**Comment by jonasstein** [comment]
works fine thank you
