### ISSUE TITLE
FR: Is HOMEPAGE different for ebuilds in the same package?

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#25]
In most cases, we expect that HOMEPAGE is the same for all ebuilds in one package.
Often this is not the case, because when updating the HOMEPAGE when the project moved it was forgotten to update the old ebuilds in the tree too.

Updating HOMEPAGE does not even require a revision bump and could be fixed easily, if at least one ebuild has a working value. Perhaps it is best combined with the HTTP status codes (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) which are available anyway:

```
404|foo/bar-1.0|http://fooo/bar
200|foo/bar-9999|https://foo.codehub.example.com/
000|foo/bar-9999|http://dyn.offlinefooo/bar
```

**Comment by mm1ke** [comment]
Good idea.. this should be simple to add.

BTW, some time ago, i think i asked on the dev mailing list for, i was already asking for some advice of how to fix such "problems". One dev knew this sort of problem, but mentioned that actually the HOMEPAGE variable shouldn't be in the ebuild at all, which i can only agree on.
Even better would be if we could put them into the ```metadata.xml``` alongside with the DESCRIPTION variable.
This way we could get rid of alot of redundancy. What do you think about it? I know this isn't a easy change, and in the short term i will make a script which looks for different homepages in same packages. But I think this is something we should look further into...

**Comment by jonasstein** [comment]
I think I have read about that. I will add details here when I found it out. 
Anyway, if we have all HOMEPAGEs per package in sync, we can copy them to metadata by a simple script. Changing EAPI<=6 is not worth it, but it could get part of EAPI=7 not to contain the HOMEPAGE anymore. But this is on longer timescales... We still have EAPI<3 packages :(

**Comment by mm1ke** [comment]
Yes, good idea.

BTW, below the code i'll gonna include in the wwwtest script:
```for i in $(curl -s http://gentoo.levelnine.at/wwwtest/full.txt | cut -d'|' -f 2|sort -u); do if [ "$(grep "HOMEPAGE=" /usr/portage/metadata/md5-cache/${i}-[0-9]*|cut -d'=' -f2|sort -u|wc -l)" -gt 1 ]; then curl -s http://gentoo.levelnine.at/wwwtest/full.txt| grep "|$i|"; fi ; done```

You can copy paste it right now to see the expected result. (Warning: It's slow, better would be to download the full.txt file and grep locally ;) )
I'll do the result into special directory under wwwtest, sorted in category/package.txt

PS: This code is very simple and even finds difference like missing/added '/' at the end of a homepage.

**Comment by mm1ke** [comment]
Ok, we'll see how it looks like: it's gonna be under special/unsync-homepages :)

**Comment by simonvanderveldt** [comment]
I think this was added in https://github.com/mm1ke/gentoo-scripts/commit/8d00bb5b40ba6f28e3689fe1d77cbde98d60b6a2?

**Comment by mm1ke** [comment]
Yes, this is already running for weeks.. Gonna close this FR.
