### ISSUE TITLE
FR: .zip dependency missing

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#34]
If `SRC_URI` downloads a .zip or similar, we need a dependency on app-arch/unzip in all ebuilds EAPI=1-6. I do not know about 7.

There may be a few strange false positives. For example, if it is a zipped plugin and the program can unzip itself. But this will be very seldom.

**Comment by mm1ke** [comment]
Nice idea. Clearly something to check :)

**Comment by mm1ke** [comment]
This will be checked with srctest now. Results should be available from tomorrow.

**Comment by jonasstein** [comment]
update: ulm confirmed today on IRC, that nothing changed for EAPI=7.

**Comment by mm1ke** [comment]
@jonasstein thanks for the confirmation :)
This should be fine now, gonna close this.
