### ISSUE TITLE
false positive SF: 301

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#4]
looks to me like a false positive, did I miss something?
http://gentoo.levelnine.at/wwwtest/sort-by-package/app-editors/nedit.txt

**Comment by mm1ke** [comment]
Hmm, good catch.
Yes, thats seems like an false positive, even though curl reports 301 as http code. Don't know if it's a porblem with curl or a DNS/sourceforge problem. I've tested it from two different internet connections, but still get a 301.

However, this should be easy to fix. With curl i can also look up for the redirected url.
I'll gonna create another check, and compare actual with redirected url. If it match (which btw matches with nedit), i gonna rewrite the code as 200...

Just give me some time to adept this.

**Comment by jonasstein** [comment]
It is the **missing slash in the end**. 
Perhaps worth to group these too? Most 301 are http -> https and missing slash in the end.
When we have groups per user with these bugs, and the textfile includes the package name, we can automate things.

**Comment by mm1ke** [comment]
lol, didn't saw that either.
Thanks for the info.
I've added new features now, which should help here. The script now checks every 301 code if the site just misses a "/", "www." or "https" (+ some combinations). If the return code is 200 it gets saved into: http://gentoo.levelnine.at/wwwtest/special/301_slash_httpS_www.txt (with category/package and maintainers)
You could easily grep this file to see which packages belong to which maintainer. Would this help?

BTW, if the code isn't 200 it creates another file (http://gentoo.levelnine.at/wwwtest/special/301_redirections.txt) were it writes the new homepage + also it's http_code (some link to a dead page)

What do you think.

PS: I've started the script now.. So it still runs for quite some time ;)

**Comment by jonasstein** [comment]
Thank you. That is not bad.
Next, it would be good, to improve the file format, so that it is better to grep and cut. Double TAB or `->` are bad for slicing. What do you think about `;` as delimiter? In most cases one needs the package name. so it would be nice to have the category/package as first or second field.

**Comment by mm1ke** [comment]
Sure, `;` is perfectly fine.
To be honest, i haven't thought about to use the results more that just a bit grepping. Basically i was more concerned about readability. However, I'll gonna change it and also put the category/package at the front. 

I'll let you know when it's live.

**Comment by mm1ke** [comment]
Hi, i've updated the script now. Tomorrow we will see how it looks. Delimiter is now a `;` and the ordering looks like this:
category;package;ebuild;http-code;homepage;maintainer (it's diferently for the "special" files, however, i've added a data-usage file)

I've also changed the script in order to use the md5-cache if available (if you sync the tree by git it's not available). So from tomorrow we shouldn't have any pages in VAR.txt anymore :D
