### ISSUE TITLE
FR: RESTRICT=mirror + SRC_URI = fatal bug

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#41]
#I suggest to test, if RESTRICT mirror is set for any in the list with broken SRC_URI
These packages are unable to be installed and should be fixed soon, or last rited.
Important would be to know if the package is already masked.

**Comment by mm1ke** [comment]
This will be checked with srctest now. Results should be available from tomorrow. However it won't check for already masked packages (yet).

**Comment by mm1ke** [comment]
This should be fine now, gonna close this.
