### ISSUE TITLE
False positive: SRC_URI not found, if there are alternatives and some work and some fail

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#44]
We have a problem on Gentoo, that there is no general dist file directory. This leads to workarounds like seen in https://bugs.gentoo.org/642102
I have no good idea, but it should be documented and kept in mind.
Until we have a solution, I suggest to white list the package.

**Comment by mm1ke** [comment]
Hi, i've fixed this in https://github.com/mm1ke/gentoo-scripts/commit/141c71044e8909ea54157479c82fe4842c2f1fed

For now i just whitelist those particular packages. This reduces false positives quite alot.
