### ISSUE TITLE
FR: Go to home link

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#45]
I suggest to add a link  `go to home page` on each page. 
Example:

```
List generated on 2018-02-24
Total Maintainers: 207
go to home page
```
This helps people to find out more statistics, if they got only a link to a deep page.

**Comment by mm1ke** [comment]
Yes, definitely..
I've already planed that anyway, but haven't included this into the test page. (as it's simple to implement anyway)

**Comment by mm1ke** [comment]
The actual html generation contains a go to home page button. Please have a look at https://gentooqa.levelnine.at/results/checks/
