### ISSUE TITLE
FR: lists sorted by number

### ISSUE THREAD

**Issue by hanetzer** [mm1ke/gentoo-scripts#49]
Taking [this](https://gentooqa.levelnine.at/results/gentoo/checks/SIC-BUG-ebuild_epatch_in_eapi6/index.html) page as an example, I'd like to have an alt version which sorts the list by QTY instead
of Maintainer. This is quasi-related to my previous feature request, as it would allow the 'juiciest'
targets to float to the top for folks looking for QA issues that can be fixed in bulk.

**Comment by mm1ke** [comment]
sounds like a good idea, which shouldn't be too difficult to change. I'm not going to add another view but only change the current one.
I have some time this weekend so i'll try to fix your requests :)

**Comment by hanetzer** [comment]
Many thanks, will make my binge QA-ing easier in the future.

**Comment by mm1ke** [comment]
Ok, this should be fixed, the listing is now sorted by QTY.

**Comment by mm1ke** [comment]
This should be fine now, gonna close this.
