### ISSUE TITLE
FR: obsolete repository

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#5]
A current list of obsolete links to HTTP, SRC_URI of obsolete repositories would fit well in to this suit.

https://wiki.gentoo.org/wiki/Upstream_repository_shutdowns

**Comment by mm1ke** [comment]
Done. 

The script now cerates separate files for each shutdown repo. The script is currently running, but you should see the result here: http://gentoo.levelnine.at/wwwtest/sort-by-filter/

Let me know what you think.

About SRC_URI: I already though about checking SRC_URI too. However, i wanted to create a separate script about that. Main problem with SRC_URI links: All the variables in it's ebuild. Vars like ${P}, ${PN}... are easy to replace, but many have special vars ${MY_PN} or Variable expansion / Substring replacements. That's difficult to replace.. at least for me..

**Comment by jonasstein** [comment]
even worse: some ebuilds do not use `SRC_URI` directly `EGIT_REPO_URI="https://github.com/${PN}/${PN}"`
You can look at the metadata cache:
`cd /usr/portage/metadata/md5-cache`
In this folder `HOMEPAGE` and `SRC_URI` are already evaluated. I used it in scripts on around the shutdown problem a lot: https://wiki.gentoo.org/wiki/Upstream_repository_shutdowns

**Comment by mm1ke** [comment]
Huh, i was aware of the md5-cache but haven't though about using it. But yes.. that's a great idea.
Thank you for the tip. Actually a bit embarrassing. I clearly gonna look into it :)

**Comment by mm1ke** [comment]
Ok, srctest.sh is live now.. Tomorrow we have SRC_URI results as well :)
The script is maybe not yet perfect, but it should be a good start.
