### ISSUE TITLE
FR: detailed EAC-STA-ebuild_obsolete_eapi breakdown

### ISSUE THREAD

**Issue by hanetzer** [mm1ke/gentoo-scripts#50]
I would like the above mentioned check to have suboptions to say list only EAPI=0 ebuilds, for
EAPI=[01234].

**Comment by mm1ke** [comment]
ok, this shouldn't be a problem. However, can you have a look at: https://gentooqa.levelnine.at/results/gentoo/stats/EAS-STA-ebuild_eapi_statistics/sort-by-eapi/
Maybe this already fits your need? The lists only miss the second column with the other EAPI's of a given package.

**Comment by hanetzer** [comment]
its close, to be sure, but it doesn't have a number of listed ebuilds per developer per eapi, though
the size column can approximate that a bit.

**Comment by mm1ke** [comment]
Ok, this is easy to change, i'll gonna update it today so you should have the same view as the checks itself.
Hope that is enough for you. :)

**Comment by hanetzer** [comment]
Nice, thanks a lot. You're really enabling my addiction :>

**Comment by mm1ke** [comment]
Gonna close this, please reopen if you have some further ideas :)
