### ISSUE TITLE
FR: live ebuilds not on latest EAPI

### ISSUE THREAD

**Issue by hanetzer** [mm1ke/gentoo-scripts#52]
Live ebuilds are by definition in constant flux, as you'll get a different result each time you build
them for the most part. By adding them to your package.accept_keywords you effectively opt in
to this inherent instability. As such, they are the perfect place to bump EAPI in-place, without
revbumps or the like.

I'd like a listing of all live ebuilds that are not EAPI 6 for now, and 7 once that's finalized and support
is added to portage and eclasses, so we can advance the usage.

**Comment by mm1ke** [comment]
Yes, i already though about that too. Thanks for reminding me.
I'll try to include such a list as soon as possible.

**Comment by mm1ke** [comment]
Done :)
Please have a look at https://gentooqa.levelnine.at/results/gentoo/stats/EAS-STA-ebuild_eapi_live_statistics/

**Comment by hanetzer** [comment]
Looks good :)

**Comment by mm1ke** [comment]
I'm going to close this. Please open a new FR if you have further ideas :)
