### ISSUE TITLE
Deptree for eclasses?

### ISSUE THREAD

**Issue by hanetzer** [mm1ke/gentoo-scripts#55]
Not something I'd think would go well with the levelnine qa reports site, but I figure
you'd be able to help me out here; per a discussion with mattst88 in #gentoo-desktop,
we're working on getting the xorg-2/x11@g.o ebuilds up to EAPI 7. There are about
300 ebuilds which use xorg-2.eclass, I was hoping you could help out with some script
to put together a deptree for these eclasses, so one could start at the root and work
to the branches.

**Comment by mm1ke** [comment]
Not sure yet what exact output you are hoping for? Could you give me some example?

I saw you're xorg-2 removal / EAPI 7 bump PR, so i guess the main motivation is to get rid of the ```xorg-2``` eclass. 
Do you want a "simple" deptree of the 300 packages (not implying it is simple to code) or has the eclass some special magic which i have to consider as well?
As i was already thinking about a general deptree generation script for eclasses (i would like to know which eclasses inherit other eclasses) and later maybe a deptree script for all packages (huge, but should be doable too) i might can help you here too ;)

**Comment by hanetzer** [comment]
Basically I know some ebuilds using xorg-2 are closer to the 'root' of all x11
packages, and need to be handled before going higher up the tree. The eclass
has a bit of magic in it but its not enough to be worth scripting out or too much
to manually figure out when I have a larger tree to work against. If things go as
they have for me so far, I may very well be real close to being done before this
gets done, but it may be of use for other projects as well :+1:

**Comment by mm1ke** [comment]
Hi,

I've wrote a small tool to find out which eclass a eclass inherits. The script is under tools and is called ```dteclass.sh```. The output looks like following:

```
ai@x1 ~/coding $ ./dteclass.sh eutils
eutils.eclass
        | desktop
        | epatch
        | estack
        | ltprune
                | toolchain-funcs
                        | multilib
!C                              | CIRCULAR DEEP with toolchain-funcs
        | multilib
                | toolchain-funcs
!C                      | CIRCULAR DEEP with multilib
        | preserve-libs
        | toolchain-funcs
                | multilib
!C                      | CIRCULAR DEEP with toolchain-funcs
        | vcs-clean
```

The ```!C``` means there is a circular deependency with another eclass. You'll will see that often, but it's mostly only for ```multilib``` and ```toolchain-funcs```.. which is known by the devs, see [1]


[1] https://bugs.gentoo.org/661764

**Comment by hanetzer** [comment]
@mm1ke beautiful, you da man!
