### ISSUE TITLE
FR: breakdown of cmake-multilib usage by maintainer/etc

### ISSUE THREAD

**Issue by hanetzer** [mm1ke/gentoo-scripts#57]
cmake-multilib is fairly unused (22 eapi 5 and 142 eapi 6 ebuilds as of right
now according to qa-reports.gentoo.org) and creates an additional overhead
when adding new eapi support to multilib cmake ebuilds instead of using
multilib-minimal and cmake-utils directly. Hoping to make a series of prs by
maintainer to unwrap it into a more plain format, as we dont use eclasses
like this for other build systems (autotools-multlib exists but its banned in
eapi 6 or greater). Also would be good to also have autotools-multilib,
qt4-build-multilib (dead) and mysql-multilib-r1 in this listing as well.

**Comment by mm1ke** [comment]
https://gentooqa.levelnine.at/results/gentoo/stats/ECS-STA-ebuild_eclass_statistics/sort-by-filter/cmake-multilib.eclass/index.html - Is that list sufficient?
You'll find results for all other eclasses here: https://gentooqa.levelnine.at/results/gentoo/stats/ECS-STA-ebuild_eclass_statistics/sort-by-filter/
Let me knoe if you still miss something ;)

**Comment by mm1ke** [comment]
closing this as it's already fixed
