### ISSUE TITLE
FR: dataformat

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#6]
The dataformat is now
`sys-apps;fwts;fwts-17.02.00;403;https://wiki.ubuntu.com/Kernel/Reference/fwts;maintainer-needed@gentoo.org:`
I suggest to change it to

`403;sys-apps/fwts;fwts-17.02.00;https://wiki.ubuntu.com/Kernel/Reference/fwts;maintainer-needed@gentoo.org:`
because the first key is better to sort and search for. 
The category/package should be written with / `sys-apps/fwts`

ps: I know that already several packages were fixed on basis of your list.

**Comment by mm1ke** [comment]
Done,

From tomorrow the result are formatted as you written.
And Thanks for the Info. Good to know people can use it :)
