### ISSUE TITLE
Website should indicate some sort of contact details (github, dev names, etc)

### ISSUE THREAD

**Issue by kentfredric** [mm1ke/gentoo-scripts#60]
I tried looking through the page: No luck
I tried looking through the page source: No luck
I tried looking at whois data: No luck

Though with even more persistence, I found it on like, page 8 of google search results for something.

But even then I wasn't sure, and had to ask somebody on a gentoo IRC channel.

It would be nice if there was some sort of "and here's the github for this page if you have issues/suggestions", or alternatively, at very minimum, some IRC aliases for gentoo dev's to harass. 

( This criticism aside, its a very useful website :) )

**Comment by mm1ke** [comment]
Hi Kent,

Again, thanks for the input. 
Yes i really should add some contact details. I'll add some information to the site soon(tm). :)

**Comment by mm1ke** [comment]
I've now added a very simple about page, which should be live tomorrow. It points to this github page and also includes my contact details (email)
