### ISSUE TITLE
date math confused by reverts of older revision

### ISSUE THREAD

**Issue by kentfredric** [mm1ke/gentoo-scripts#63]
Ouch:

> https://gentooqa.levelnine.at/results/gentoo/stats/EAC-STA-ebuild_cleanup_candidates/sort-by-maintainer/perl_at_g.o.txt
```
5|00078|7|00129|-|dev-perl/AutoXS-Header|AutoXS-Header-1.20.0-r1(2020-06-20)|AutoXS-Header-1.20.0-r2(2020-04-30)|perl@gentoo.org
```

Its correct that its a cleanup candidate, just the timestamp math is ... spooky.

I spotted it because I parse and reformat the line as follows:

```
  dev-perl/                           AutoXS-Header    1.20.0-r1 →    1.20.0-r2 ( 2020-06-20 → 2020-04-30 ) <   00078 →   00129 (diff:     -51)
```

The data is not exactly wrong ... its just really not what I expected, and I don't know what should be done about this, if at all.

I just sort of expected it would track as if the removal and revert of removal never happened.

**Comment by kentfredric** [comment]
Though I guess this bug serves as a second vote for https://github.com/mm1ke/gentoo-scripts/issues/62, as if I'd been tracking "age of last change" instead of "age of addition to tree", the ages would have been logical :smile:

**Comment by mm1ke** [comment]
Huh.. nice catch.. :smile: 
But i think i could fix this.
```
git log --format="format:%ci" --diff-filter=A AutoXS-Header-1.20.0-r1.ebuild
```
which prints
```
2020-06-20 16:55:06 +1200
2016-06-15 11:34:48 +0600
```

this only prints the added dates of a particular file (which i'm already using right now), but instead of using the newest date i simply can use the oldest. I need to check if that might has some downsides but i think it should be fine.

**Comment by mm1ke** [comment]
Ok, so this should be fixed from tomorrow on. As mentioned, i'll simply use the older date value. So far i don't see a reason why the newer value would be interesting and it shouldn't break anything.

**Comment by mm1ke** [comment]
closing this as well, this shouldn't be a problem anymore :)
