### ISSUE TITLE
Consider running scripts for GURU overlay

### ISSUE THREAD

**Issue by telans** [mm1ke/gentoo-scripts#65]
It would be great to get an output for the GURU overlay much like kde/science etc. Thanks.

**Comment by mm1ke** [comment]
Hi, sure, i'll add it. Just give me 2-3 days and you should see the result.
I'll keep the issue open until the results are up.

**Comment by mm1ke** [comment]
just wanted to inform you that the results are online now but i guess you already noticed ;)
