### ISSUE TITLE
FR: list packages with gentoo mirror as source

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#8]
https://devmanual.gentoo.org/general-concepts/mirrors/ 

> Previous policy was to use mirror://gentoo directly, but this is now deprecated, as that wouldn't allow to have long-term availability and traceability of the source files, which might be a requirement of the license. 

Packages with this problem can be listed by
`qgrep -N 'SRC_URI="mirror://gentoo'`

Especially for the sorted-by-maintainer folder it would be useful to list these too

**Comment by mm1ke** [comment]
You should have results tomorrow under simplechecks/gentoo_mirror_missuse/ :)

I've put it into the simplechecks script. Even though qgrep would be slightly faster i haven't used it because this way i don't have implement something new to parse the qgrep output ;)
